# Generated by Django 5.1.4 on 2025-01-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_taskmodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='user_id',
        ),
    ]
